# Bulk RNA differential expression script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Bio_Bulk_align_group(): sample/group alignment
# - Bio_Bulk_filter_low_expression(): low-expression filtering
# - Bio_Bulk_limma_analysis(): reference DEG implementation
# MedNova keeps the first-version template aligned with the unified bulk entry.
# Review the count matrix, sample metadata, and contrast before running.

count_matrix <- {{COUNT_MATRIX_NAME}}
group_data <- {{COL_DATA_NAME}}

bulk_res <- med_bulk_deg(
  counts = count_matrix,
  group = group_data,
  group_col = {{GROUP_COLUMN}},
  case_name = {{CASE_LEVEL}},
  control_name = {{CONTROL_LEVEL}}
)

utils::head(bulk_res$deg$results)
