# Cox regression script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Epi_cox_multiv(): primary Cox model
# - Epi_cox_ph_test(): proportional hazards test
# - Epi_timeROC(): time-dependent ROC evaluation
# This template intentionally keeps only the minimal fit step for first-version generation.
# Review the time, event, and predictor columns before running.

analysis_data <- {{DATA_NAME}}

cox_formula <- stats::as.formula({{COX_FORMULA}})

cox_fit <- survival::coxph(
  formula = cox_formula,
  data = analysis_data
)

summary(cox_fit)
