# Diagnostic modeling script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Bio_build_diagnostic_model(): multigene logistic model with nomogram and DCA
# - plot_diagnostic_roc(): ROC plotting workflow
# - Bio_RF_train(): random forest diagnostic classifier
# - Epi_nomogram_logistic(), Epi_calibration_bootstrap(), Epi_DCA(): model interpretation and utility checks
# This template remains intentionally basic and uses logistic regression plus ROC only.
# Review the outcome and predictors before running.

analysis_data <- {{DATA_NAME}}

diagnostic_formula <- stats::as.formula({{MODEL_FORMULA}})

diagnostic_fit <- stats::glm(
  formula = diagnostic_formula,
  data = analysis_data,
  family = stats::binomial()
)

predicted_prob <- stats::predict(diagnostic_fit, type = "response")
roc_obj <- pROC::roc(analysis_data[[{{OUTCOME_COLUMN}}]], predicted_prob, quiet = TRUE)
auc_value <- pROC::auc(roc_obj)

summary(diagnostic_fit)
auc_value
