# Logistic regression script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Epi_logistic_multiv(): primary multivariable model
# - Epi_logistic_univ(): univariable screening
# - Epi_logistic_vif(): collinearity check
# - Epi_hoslem_test(): goodness-of-fit assessment
# - plot_logistic_forest(): OR visualization
# This template remains a small runnable baseline instead of a full wrapper.
# Review the outcome and predictors before running.

analysis_data <- {{DATA_NAME}}

model_formula <- stats::as.formula({{MODEL_FORMULA}})

logistic_fit <- stats::glm(
  formula = model_formula,
  data = analysis_data,
  family = stats::binomial()
)

summary(logistic_fit)
utils::head(stats::predict(logistic_fit, type = "response"))
