# Mendelian randomization script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Bio_MR_format_exposure() / Bio_MR_prepare_outcome(): data formatting
# - Bio_MR_harmonize_one(): allele harmonization
# - Bio_MR_run_methods() / Bio_MR_run_single(): MR estimation and sensitivity outputs
# - Bio_MR_pipeline(): high-level workflow with file-writing side effects in the reference package
# This template stays side-effect-light and only generates core runnable code.
# Review exposure and outcome summary datasets before running.

exposure_dat <- {{EXPOSURE_DATA_NAME}}
outcome_dat <- {{OUTCOME_DATA_NAME}}

harmonised_dat <- TwoSampleMR::harmonise_data(
  exposure_dat = exposure_dat,
  outcome_dat = outcome_dat
)

mr_results <- TwoSampleMR::mr(harmonised_dat)

mr_results
