# Propensity score matching script generated by MedNova
# Reference mapping from _reference/EpiBioToolkit:
# - Epi_PSM_match(): core matching wrapper
# - Epi_PSM_baseline_tables(): before/after baseline summaries
# - plot_love(): balance visualization after matching
# This template stays minimal on purpose and does not call the reference package directly.
# Review treatment and covariates before running.

analysis_data <- {{DATA_NAME}}

psm_formula <- stats::as.formula({{PSM_FORMULA}})

matched_fit <- MatchIt::matchit(
  formula = psm_formula,
  data = analysis_data,
  method = "nearest",
  distance = "logit"
)

matched_data <- MatchIt::match.data(matched_fit)

summary(matched_fit)
utils::head(matched_data)
